### ISSUE TITLE
Will this be updated to be compatible with ChartJS 3.0?

### ISSUE THREAD

**Issue by jackyaz** [chartjs/chartjs-plugin-deferred#15]

**Comment by gregh3269** [comment]
v3.1.0 I get
Uncaught TypeError: Chart.defaults.global is undefined
/**
 * Plugin based on discussion from Chart.js issue #2745.
 * @see https://github.com/chartjs/Chart.js/issues/2745
 */
Chart.defaults.global.plugins.deferred = {
	xOffset: 0,
	yOffset: 0,
	delay: 0
};

**Comment by john-rock** [comment]
Chartjs version: 3.3.2
Plugin version: 1.0.2

 I'm getting - `e.defaults.global is undefined`

**Comment by gregh3269** [comment]
Would be good to get this fixed as @2.9.4 is the last version plug-in works on.

**Comment by cysieks** [comment]
I was able to change it to work with chart.js > 3

https://github.com/cysieks/chartjs-plugin-deferred

**Comment by cysieks** [comment]
I was able to make it work with chart js 3:
Here is fork: https://github.com/cysieks/chartjs-plugin-deferred

**Comment by gregh3269** [comment]
Great, works for me, maybe this is not abandoned here yet, possibly do a PR?  ...so CDN's work.

**Comment by mloit** [comment]
The parameter lists for the `beforeInit`, and `beforeDatasetsUpdate` are incorrect. As coded they are `(chart, options)`, but they need to be `(chart, args, options)` for the `options` to be seen, without it it is defaulting to 0 because it thinks they are undefined.. Changing that seems to have made it work for me. I had to make some other changes to get it to load, but once i did that, it all seems to work now. @cysieks  thanks for the fork!

**Comment by simonbrunel** [comment]
[Version 2.0.0-beta.1](https://github.com/chartjs/chartjs-plugin-deferred/releases/tag/v2.0.0-beta.1) has been released and is compatible with Chart.js v3.
